=== bearsunday/BEAR.ApiDoc/apidoc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation> BEAR.Sunday API document tool config</xs:documentation>
        <xs:appinfo source="https://github.com/bearsunday/BEAR.ApiDoc"/>
    </xs:annotation>
    <xs:element name="apidoc">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="appName"/>
                <xs:element ref="scheme"/>
                <xs:element ref="docDir"/>
                <xs:element ref="format"/>
                <xs:element ref="title" minOccurs="0"/>
                <xs:element ref="description" minOccurs="0"/>
                <xs:element ref="links" minOccurs="0"/>
                <xs:element ref="alps" minOccurs="0"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="appName" type="xs:string">
        <xs:annotation>
            <xs:documentation>Application namespace ex) MyVendor\MyProject.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="scheme">
        <xs:annotation>
            <xs:documentation>Resource scheme: app or page</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="app"/>
                <xs:enumeration value="page"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="docDir" type="xs:string">
        <xs:annotation>
            <xs:documentation>API Doc output directory</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="format">
        <xs:annotation>
            <xs:documentation>Output document format</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="html"/>
                <xs:enumeration value="md"/>
                <xs:enumeration value="openapi"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="title" type="xs:string">
        <xs:annotation>
            <xs:documentation>API doc title</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="description" type="xs:string">
        <xs:annotation>
            <xs:documentation>API doc description</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="links" type="linksType" >
        <xs:annotation>
            <xs:documentation>Link list</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="linksType">
        <xs:sequence>
            <xs:element name="link" type="linkType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="linkType">
        <xs:attribute name="href" type="xs:string">
            <xs:annotation>
                <xs:documentation>Link URL</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="rel" type="xs:string">
            <xs:annotation>
                <xs:documentation>Link Description</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:element name="alps" type="xs:string">
        <xs:annotation>
            <xs:documentation>ALPS link</xs:documentation>
        </xs:annotation>
    </xs:element>
</xs:schema>

=== bearsunday/BEAR.ApiDoc/tests/apidoc.md.xml
<?xml version="1.0" encoding="UTF-8"?>
<apidoc
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../apidoc.xsd">
    <appName>FakeVendor\FakeProject</appName>
    <scheme>app</scheme>
    <docDir>docs/md</docDir>
    <format>md</format>
    <title>Markdown API Docs</title>
    <links>
        <link rel="home" href="https://example.com" />
    </links>
</apidoc>

=== bearsunday/BEAR.ApiDoc/tests/apidoc.alps.xml
<?xml version="1.0" encoding="UTF-8"?>
<apidoc
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../apidoc.xsd">
    <appName>FakeVendor\FakeProject</appName>
    <scheme>app</scheme>
    <docDir>docs/html</docDir>
    <format>html</format>
    <title>API Doc Title</title>
    <description>This is the description of API Doc</description>
    <links>
        <link rel="doc" href="http://www.google.com/" />
        <link rel="foo" href="http://www.google.com/" />
    </links>
    <alps>alps.json</alps>
</apidoc>

=== bearsunday/BEAR.ApiDoc/tests/apidoc.html.xml
<?xml version="1.0" encoding="UTF-8"?>
<apidoc
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../apidoc.xsd">
    <appName>FakeVendor\FakeProject</appName>
    <scheme>app</scheme>
    <docDir>../docs</docDir>
    <format>html</format>
    <title>API Doc Title</title>
    <description>This is the description of API Doc</description>
    <links>
        <link rel="home" href="https://github.com/bearsunday/BEAR.ApiDoc" />
        <link rel="issues" href="https://github.com/bearsunday/BEAR.ApiDoc/issues" />
        <link rel="profile" href="alps.html" />
        <link rel="openapi" href="openapi/" />
        <link rel="audit" href="audit.html" />
    </links>
    <alps>../docs/alps.json</alps>
</apidoc>

=== bearsunday/BEAR.ApiDoc/tests/apidoc.demo-terms.xml
<?xml version="1.0" encoding="UTF-8"?>
<apidoc
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../apidoc.xsd">
    <appName>FakeVendor\FakeProject</appName>
    <scheme>app</scheme>
    <docDir>../docs</docDir>
    <format>terms</format>
    <title>Term Usage Index</title>
    <description>Term usage index for the demo API</description>
    <alps>../docs/alps.json</alps>
</apidoc>

=== bearsunday/BEAR.ApiDoc/tests/apidoc.audit.xml
<?xml version="1.0" encoding="UTF-8"?>
<apidoc
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../apidoc.xsd">
    <appName>FakeVendor\FakeProject</appName>
    <scheme>app</scheme>
    <docDir>docs/audit</docDir>
    <format>audit</format>
    <title>API Doc Title</title>
    <description>This is the description of API Doc</description>
    <alps>Fake/app/alps.json</alps>
</apidoc>

=== bearsunday/BEAR.ApiDoc/tests/apidoc.terms.xml
<?xml version="1.0" encoding="UTF-8"?>
<apidoc
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../apidoc.xsd">
    <appName>FakeVendor\FakeProject</appName>
    <scheme>app</scheme>
    <docDir>docs/terms</docDir>
    <format>terms</format>
    <title>API Doc Title</title>
    <description>This is the description of API Doc</description>
    <alps>profile.json</alps>
</apidoc>

=== bearsunday/BEAR.ApiDoc/tests/apidoc.demo-audit.xml
<?xml version="1.0" encoding="UTF-8"?>
<apidoc
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../apidoc.xsd">
    <appName>FakeVendor\FakeProject</appName>
    <scheme>app</scheme>
    <docDir>../docs</docDir>
    <format>audit</format>
    <title>API Documentation Audit</title>
    <description>Documentation coverage report for the demo API</description>
    <alps>../docs/alps.json</alps>
</apidoc>
